<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="GlobalHotKeys.Windows" />
		<PackageReference Include="MouseKeyHook" />
		<PackageReference Include="sharphook" />
		<PackageReference Include="sharphook.reactive" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="System.Reactive" />
		<PackageReference Include="NHotkey.WindowsForms" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\WinTabber.Interop\WinTabber.Interop.csproj" />
	</ItemGroup>
</Project>
