<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <UseWPF>true</UseWPF>
        <Platform>x64</Platform>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="ShortcutCommands.json" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="ShortcutCommands.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" />
        <PackageReference Include="ReactiveUI" />
        <PackageReference Include="System.Runtime.Caching" />
        <PackageReference Include="TaskScheduler" />
        <PackageReference Include="Microsoft.Windows.CsWin32">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Remove="NativeMethods.txt" />
        <AdditionalFiles Include="NativeMethods.txt" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\WinTabber.Api.Media\WinTabber.Api.Media.csproj" />
        <ProjectReference Include="..\WinTabber.Events\WinTabber.Events.csproj" />
        <ProjectReference Include="..\WinTabber.Interop\WinTabber.Interop.csproj" />
    </ItemGroup>
</Project>
