<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.5.78" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinTabberUI\WinTabberUI.csproj" />
  </ItemGroup>

</Project>