<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinTabber.Api.Media\WinTabber.Api.Media.csproj" />
    <ProjectReference Include="..\WinTabber.Events\WinTabber.Events.csproj" />
    <ProjectReference Include="..\WinTabber.Infrastructure\WinTabber.Infrastructure.csproj" />
    <ProjectReference Include="..\WinTabber.UI.Common\WinTabber.UI.Common.csproj" />
  </ItemGroup>

</Project>