<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Platform>x64</Platform>

		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\icon.psd" />
	  <None Remove="Images\loading.png" />
	  <None Remove="Images\logo-small.ico" />
	  <None Remove="Images\logo.ico" />
	  <None Remove="Images\logo.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Hints\GeneratedHintsProvider.cs" />
	</ItemGroup>



	<ItemGroup>
	  <Resource Include="Images\icon.jpg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\icon.psd">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\loading.png" />
	  <Resource Include="Images\logo-small.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\logo.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Images\logo.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="AutomaticInterface" Version="5.2.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="fontawesome.sharp" Version="6.6.0" />
		<PackageReference Include="GlobalHotKeys.Windows" Version="0.1.0" />
		<PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.2" />
		<PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
		<PackageReference Include="Material.Icons.WPF" Version="2.4.1" />
		<PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.205">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MouseKeyHook" Version="5.7.1" />
		<PackageReference Include="NAudio.WASAPI" Version="2.2.1" />
		<PackageReference Include="ReactiveUI" Version="22.3.1" />
		<PackageReference Include="TaskScheduler" Version="2.12.2" />
		<ProjectReference Include="..\WinTabber.Generators\WinTabber.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Include="reactiveui.wpf" Version="22.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WinTabber.API\WinTabber.API.csproj" />
		<ProjectReference Include="..\WinTabber.Events\WinTabber.Events.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Update="NativeMethods.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</AdditionalFiles>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="Resources\Theme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Infrastructure\NewFolder\" />
	  <Folder Include="Factories\" />
	</ItemGroup>

</Project>
